version: "3.7"
services:
  redis:
    image: redislabs/redismod
    container_name: flask_redis
  app:
    build: .
    container_name: flask
    command: python app.py  --host=0.0.0.0 --reload
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    depends_on:
      - redis
