INSERT INTO targets (title, image_url, description, summary, key_point_list)
VALUES ('Unity 游戏开发', 'https://blog.logrocket.com/wp-content/uploads/2022/08/design-level-probuilder-unity-1.png',
        'Unity是一款非常流行的跨平台游戏开发引擎，它可以用来开发2D和3D游戏，支持多种平台，包括Windows、Mac、iOS、Android等。如果你想开始学习Unity游戏开发，以下是一些基本步骤和资源，可以帮助你入门：',
        '学习Unity游戏开发需要时间和耐心，但一旦你掌握了基本概念，你就可以开始创建自己的游戏项目。不断练习和尝试新的功能和技术将有助于提高你的技能。祝你在Unity游戏开发中取得成功！',
        '["1. 下载和安装Unity：访问Unity官方网站（https://unity.com/）并下载Unity Hub，然后使用Unity Hub安装Unity编辑器。", "2. 学习C#编程语言：Unity主要使用C#编程语言来编写游戏逻辑。如果你不熟悉C#，建议你学习一些基本的C#编程知识。有许多在线教程和资源可供学习。", "3.  学习Unity界面：熟悉Unity编辑器的界面和基本工具，包括场景编辑器、资源管理器、层次结构视图等。", "4. 创建项目：在Unity中创建一个新项目，选择适当的设置，例如2D或3D游戏，选择目标平台等。", "5.  学习Unity组件：学习Unity的组件系统，了解GameObject、Transform、Collider、Rigidbody等常用组件以及它们的作用。", "6. 编写游戏脚本：使用C#编写游戏脚本来实现游戏逻辑，例如角色控制、碰撞检测、动画等。", "7. 资源管理：导入和管理游戏资源，如模型、纹理、音效和动画。", "8. 场景设计：创建游戏场景并设置关卡布局，包括地形、道路、障碍物等。", "9. 动画和效果：添加动画和特效以增强游戏的视觉效果。", "10. 调试和测试：定期测试和调试你的游戏，确保它正常运行。", "11. 发布游戏：准备好发布你的游戏到不同的平台，如PC、移动设备或游戏主机。", "12. 学习资源：初学者可以查找在线教程、文档和Unity社区论坛，以获取更多帮助和支持。Unity的官方网站和Unity Learn平台也提供了大量免费的学习资源。"]'),
       ('Blender 模型建模',
        'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.linuxadictos.com%2Fen%2Fubisoft-and-epic-games-will-use-blender.html&psig=AOvVaw2Y5uANtZwnPanTadnn1se9&ust=1695197663124000&source=images&cd=vfe&opi=89978449&ved=0CA8QjRxqFwoTCNj_xsadtoEDFQAAAAAdAAAAABAE',
        'Blender 是一个强大的开源三维计算机图形软件，它提供了丰富的工具和功能，用于模型建模、渲染、动画制作、渲染和视频编辑等任务。在 Blender 中进行模型建模可以用于创建游戏角色、建筑、产品设计等各种用途。下面是一些在 Blender 中进行模型建模的基本步骤：',
        '建模是一个复杂的过程，需要不断的实践和学习。Blender 社区提供了大量的教程、文档和视频教程，可以帮助你更深入地了解模型建模和Blender软件的使用。希望这些基本步骤能够帮助你入门Blender模型建模。',
        '["1.启动 Blender：打开 Blender 软件。默认情况下，你会看到一个包含一个立方体的场景。", "2.界面导航：在 Blender 中，你可以使用鼠标中键滚轮进行缩放、按住鼠标右键进行选择、按住鼠标中键进行旋转等基本导航操作。", "3.选择基本模型：在开始建模之前，你可以选择一个基本的模型来作为你的起点，例如立方体、球体、圆柱体等。这些基本模型可以在左侧的“添加”菜单中找到。", "4.编辑模型：使用编辑模式来修改选定的模型。切换到编辑模式的方法是在左上角的模式切换器中选择“编辑模式”。在编辑模式下，你可以选择顶点、边或面，并使用各种工具来进行变形、缩放、旋转等操作。", "5.添加细节：使用各种工具来添加细节，例如分割、挤出、切割等。这些工具可以在工具栏中找到。", "6.材质和纹理：为你的模型添加材质和纹理以增强外观。在属性编辑器中，你可以为模型创建新的材质并调整其属性。", "7.渲染和预览：使用“渲染”选项来预览模型的最终外观。你可以在渲染选项中选择渲染引擎（如Cycles或Eevee）和设置渲染参数。", "8.导出模型：一旦你完成了模型，可以导出它以在其他应用程序中使用。常见的导出格式包括.obj、fbx等。", "9.动画和渲染（可选）：如果你的模型需要动画或高质量渲染，可以使用 Blender 的动画和渲染功能。", "10.保存项目：定期保存你的工作，以避免数据丢失。"]'),
       ('Flask WEB API',
        'https://exercise-jovian-careers-websit.salmonpj.repl.co/uploads/20230927100751_UtRPPKPnsPeTJdyDaBWztkTY.png',
        'Throught learn flask web api, learn how to design api for web',
        'After learn how to write flask api by chatGpt,I have a prowful improve my My programming skills.',
        '["Flask", "WEB API", "learn wth chatgpt"]')