"""empty message

Revision ID: 937162791976
Revises: e57dc6489513
Create Date: 2023-10-15 08:47:18.637494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937162791976'
down_revision = 'e57dc6489513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
